name: qwen3

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # --- Conda 核心依赖 ---
  # 指定 Python 版本和核心计算库
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - nvidia::pytorch-cuda=12.1 # [1]
  - pandas
  - scikit-learn
  - pyyaml
  - tqdm
  
  # --- Pip 依赖 ---
  # 用于安装 PyPI 中的其他库
  - pip
  - pip:
    - transformers>=4.51.0
    - peft
    - accelerate
    - datasets
    - pydantic
    - langchain
    - flash-attn --no-build-isolation
    - future
    - annotations

